[package]
name = "samuzen/profilereplication"
description = "wip"
version = "0.0.5"
license = ""
authors = ["Guto", "SamuZen"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
exclude = []

[dependencies]
profileservice = "samuzen/profileservice@1.0.2"
signal = "sleitnick/signal@1.5.0"
table-util = "sleitnick/table-util@1.2.0"
promise = "evaera/promise@4.0.0"